### ISSUE TITLE
Demo Application Not Start Using -- NPM START

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/kittenTricks#175]
Hello Team,

I have clone your demo app and trying to start on my local system using VS Code but this is showing error.... expo web browser client is open after execut NPM START but the EXPO client is stop after few second, please help.

**ERROR** :

```

Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Warning: This project contains unoptimized assets. Please run `expo optimize` in your project directory.
error Cannot find module './config'. Run CLI with --verbose flag for more details.

Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kittenTricks@2.0.0 start: `expo start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kittenTricks@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jack/.npm/_logs/2019-06-13T07_14_11_949Z-debug.log
``` 

**ERROR LOG**

```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle kittenTricks@2.0.0~prestart: kittenTricks@2.0.0
6 info lifecycle kittenTricks@2.0.0~start: kittenTricks@2.0.0
7 verbose lifecycle kittenTricks@2.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle kittenTricks@2.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jack/Desktop/root/AppDevelopment/KittenUI/kittenTricks-master/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jack/Library/Android/sdk/platform-tools/:/Users/jack/Library/Android/sdk/platform-tools/
9 verbose lifecycle kittenTricks@2.0.0~start: CWD: /Users/jack/Desktop/root/AppDevelopment/KittenUI/kittenTricks-master
10 silly lifecycle kittenTricks@2.0.0~start: Args: [ '-c', 'expo start' ]
11 silly lifecycle kittenTricks@2.0.0~start: Returned: code: 1  signal: null
12 info lifecycle kittenTricks@2.0.0~start: Failed to exec start script
13 verbose stack Error: kittenTricks@2.0.0 start: `expo start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid kittenTricks@2.0.0
15 verbose cwd /Users/jack/Desktop/root/AppDevelopment/KittenUI/kittenTricks-master
16 verbose Darwin 18.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error kittenTricks@2.0.0 start: `expo start`
22 error Exit status 1
23 error Failed at the kittenTricks@2.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by artyorsh** [comment]
Hi @IAmAbhishekTomar 

This is already known issue #171 #173 which already got a [fix](https://github.com/akveo/kittenTricks/pull/172)
Try updating to actual repo state with `git pull` and running again.

Thanks for report

**Comment by ImAbhishekTomar** [comment]
Thanks for prompt support but after using "npm run env:set -- dev && npm start -- -c" error changed.

**New Error**

```
INFO
16:06
Starting Metro Bundler on port 19005.
INFO
16:06
Your JavaScript transform cache is empty, rebuilding (this may take a minute).
ERROR
16:06
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: resolve_projpath: path `/Users/jack/Desktop/root/AppDevelopment/KittenUI/react-native-ui-kitten/src/framework/theme`: open: /Users/jack/Desktop/root/AppDevelopment/KittenUI/react-native-ui-kitten/src/framework/theme: No such file or directory. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
INFO
16:06
Tunnel ready.
ERROR
16:06
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: resolve_projpath: path `/Users/jack/Desktop/root/AppDevelopment/KittenUI/react-native-ui-kitten/src/framework/theme`: open: /Users/jack/Desktop/root/AppDevelopment/KittenUI/react-native-ui-kitten/src/framework/theme: No such file or directory
    at BunserBuf.<anonymous> (/Users/jack/Desktop/root/AppDevelopment/KittenUI/kittenTricks-master/node_modules/fb-watchman/index.js:95:23)
    at BunserBuf.emit (events.js:189:13)
    at BunserBuf.process (/Users/jack/Desktop/root/AppDevelopment/KittenUI/kittenTricks-master/node_modules/bser/index.js:292:10)
    at /Users/jack/Desktop/root/AppDevelopment/KittenUI/kittenTricks-master/node_modules/bser/index.js:247:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at Client.client.on.error (/Users/jack/Desktop/root/AppDevelopment/KittenUI/kittenTricks-master/node_modules/jest-haste-map/build/lib/WatchmanWatcher.js:103:10)
    at Client.emit (events.js:189:13)
    at BunserBuf.<anonymous> (/Users/jack/Desktop/root/AppDevelopment/KittenUI/kittenTricks-master/node_modules/fb-watchman/index.js:107:12)
    at BunserBuf.emit (events.js:189:13)
    at /Users/jack/Desktop/root/AppDevelopment/KittenUI/kittenTricks-master/node_modules/bser/index.js:249:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by artyorsh** [comment]
> after using "npm run env:set -- dev

It looks like you've tried running an `start:dev` script. You don't need using this in case you wan't debug [UI Kitten components](https://github.com/akveo/react-native-ui-kitten) changes. We use this script locally in our team. Please see [this comment](https://github.com/akveo/kittenTricks/issues/170#issuecomment-501378388)
