### ISSUE TITLE
"Expo Start" gives: Error Cannot find module './env'

### ISSUE THREAD

**Issue by mtmJaber** [akveo/kittenTricks#283]
## 🐛 Bug Report
After running "yarn" command I run the "Expo Start" command and it gives me the next error:
Error: Cannot find module './env'
Require stack:
- D:\ra\kittenTricks\metro.config.js
- D:\ra\kittenTricks\node_modules\import-fresh\index.js
- D:\ra\kittenTricks\node_modules\cosmiconfig\dist\loaders.js
- D:\ra\kittenTricks\node_modules\cosmiconfig\dist\createExplorer.js
- D:\ra\kittenTricks\node_modules\cosmiconfig\dist\index.js
- D:\ra\kittenTricks\node_modules\@react-native-community\cli\build\tools\config\readConfigFromDisk.js
- D:\ra\kittenTricks\node_modules\@react-native-community\cli\build\tools\config\index.js
- D:\ra\kittenTricks\node_modules\@react-native-community\cli\build\commands\install\install.js
- D:\ra\kittenTricks\node_modules\@react-native-community\cli\build\commands\index.js
- D:\ra\kittenTricks\node_modules\@react-native-community\cli\build\index.js
- D:\ra\kittenTricks\node_modules\react-native\local-cli\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\ra\kittenTricks\metro.config.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |    2.4.0     |

## Environment information
Windows 10 x64

**Comment by artyorsh** [comment]
`yarn env prod && expo start` in case of Expo
Thanks for posting this

**Comment by mtmJaber** [comment]
It worked. Thank you

**Comment by prideaux** [comment]
Or if using npm and not yarn...

`npm run env -- prod && expo start`
