### ISSUE TITLE
pod install fails

### ISSUE THREAD

**Issue by ethyaan** [akveo/kittenTricks#285]
## 🐛 Bug Report

Hi, I tried to run the project, based on DEV documentation, everything is fine till I reach to `pod install` inside ios directory, It fails with below information.
on MacOS mojave.

Based  on the Error, I find out this needs to have Flutter installed?
why this needs flutter? 
I installed flutter and still fails.
## To Reproduce

Detected React Native module pods for RNCMaskedView, RNDeviceInfo, RNGestureHandler, RNReanimated, RNSVG, RNScreens, react-native-appearance, react-native-safari-view, and react-native-safe-area-context
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/ehsan/.rvm/gems/ruby-2.4.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.12
        Host : Mac OS X 10.14.6 (18G3020)
       Xcode : 10.3 (10G8)
         Git : git version 2.23.0
Ruby lib dir : /Users/ehsan/.rvm/rubies/ruby-2.4.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'KittenTricks' do

  rnPrefix = "../node_modules/react-native"

  # React Native and its dependencies
  pod 'FBLazyVector', :path => "#{rnPrefix}/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "#{rnPrefix}/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "#{rnPrefix}/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "#{rnPrefix}/Libraries/TypeSafety"
  pod 'React', :path => "#{rnPrefix}/"
  pod 'React-Core', :path => "#{rnPrefix}/"
  pod 'React-CoreModules', :path => "#{rnPrefix}/React/CoreModules"
  pod 'React-RCTActionSheet', :path => "#{rnPrefix}/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', :path => "#{rnPrefix}/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "#{rnPrefix}/Libraries/Blob"
  pod 'React-RCTImage', :path => "#{rnPrefix}/Libraries/Image"
  pod 'React-RCTLinking', :path => "#{rnPrefix}/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', :path => "#{rnPrefix}/Libraries/Network"
  pod 'React-RCTSettings', :path => "#{rnPrefix}/Libraries/Settings"
  pod 'React-RCTText', :path => "#{rnPrefix}/Libraries/Text"
  pod 'React-RCTVibration', :path => "#{rnPrefix}/Libraries/Vibration"
  pod 'React-Core/RCTWebSocket', :path => "#{rnPrefix}/"
  pod 'React-Core/DevSupport', :path => "#{rnPrefix}/"
  pod 'React-cxxreact', :path => "#{rnPrefix}/ReactCommon/cxxreact"
  pod 'React-jsi', :path => "#{rnPrefix}/ReactCommon/jsi"
  pod 'React-jsiexecutor', :path => "#{rnPrefix}/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{rnPrefix}/ReactCommon/jsinspector"
  pod 'ReactCommon/jscallinvoker', :path => "#{rnPrefix}/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "#{rnPrefix}/ReactCommon"
  pod 'Yoga', :path => "#{rnPrefix}/ReactCommon/yoga"
  pod 'DoubleConversion', :podspec => "#{rnPrefix}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rnPrefix}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rnPrefix}/third-party-podspecs/Folly.podspec"

  use_native_modules!

end
```

### Error

```
NoMethodError - undefined method `strip' for nil:NilClass
/Users/ehsan/.rvm/gems/ruby-2.4.0@global/gems/typhoeus-1.1.2/lib/typhoeus/response/header.rb:50:in `process_line'
/Users/ehsan/.rvm/gems/ruby-2.4.0@global/gems/typhoeus-1.1.2/lib/typhoeus/response/header.rb:38:in `block in parse'
/Users/ehsan/.rvm/gems/ruby-2.4.0@global/gems/typhoeus-1.1.2/lib/typhoeus/response/header.rb:35:in `each'
/Users/ehsan/.rvm/gems/ruby-2.4.0@global/gems/typhoeus-1.1.2/lib/typhoeus/response/header.rb:35:in `parse'
/Users/ehsan/.rvm/gems/ruby-2.4.0@global/gems/typhoeus-1.1.2/lib/typhoeus/response/header.rb:20:in `initialize'
/Users/ehsan/.rvm/gems/ruby-2.4.0@global/gems/typhoeus-1.1.2/lib/typhoeus/response/informations.rb:226:in `new'
/Users/ehsan/.rvm/gems/ruby-2.4.0@global/gems/typhoeus-1.1.2/lib/typhoeus/response/informations.rb:226:in `headers'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:369:in `block in download_and_save_with_retries_async'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:406:in `apply'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:1205:in `apply'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:1729:in `block (2 levels) in on_resolvable'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:1582:in `evaluate_to'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:1729:in `block in on_resolvable'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:353:in `run_task'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:342:in `block (3 levels) in create_worker'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:325:in `loop'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:325:in `block (2 levels) in create_worker'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:324:in `catch'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:324:in `block in create_worker'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:1257:in `raise'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:1257:in `wait_until_resolved!'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:977:in `wait!'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:144:in `block in versions'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:471:in `concurrent_requests_catching_errors'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:121:in `versions'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:99:in `block in versions_by_source'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:98:in `each'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:98:in `each_with_object'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:98:in `versions_by_source'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:216:in `search'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `each'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/ehsan/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/Users/ehsan/.rvm/gems/ruby-2.4.0/bin/pod:23:in `load'
/Users/ehsan/.rvm/gems/ruby-2.4.0/bin/pod:23:in `<main>'
/Users/ehsan/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/ehsan/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60strip%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - NoMethodError - undefined method `recursive_predecessors' for nil:NilClass in Flutter App
   https://github.com/CocoaPods/CocoaPods/issues/9286 [closed] [6 comments]
   20 hours ago

 - Can't seem to run pod install on a fresh version of react native
   https://github.com/CocoaPods/CocoaPods/issues/9585 [closed] [1 comment]
   6 weeks ago

 - Pod install returning error
   https://github.com/CocoaPods/CocoaPods/issues/2944 [closed] [5 comments]
   20 Nov 2019

and 4 more at:
https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60strip%27%20for%20nil&type=Issues&utf8=✓

## Expected behavior

It should work but it fails to install.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |        |
| @ui-kitten/components   |         |

## Environment information

npx envinfo --preset react-native

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 26, 29
      Build Tools: 27.0.1
  IDEs:
    Android Studio: 3.0 AI-171.4408382
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild

```bash

```

**Comment by ethyaan** [comment]
Okay,
I figured out what is the cause and how to solve it.
when you enter `pod install` it will try to connect to a repository and fetch some data `specs` and for some reason that repository is not available or it sneds the wrong response format and this will cause the failure.

how to solve it?
after a day googling about it, I found the answer here
[https://github.com/CocoaPods/CocoaPods/issues/9303](url)

since that repository doesn't work, your `pod install` will fail.
but there is a solution, all of those specs are available under a git repository.
by adding the following line to your `Podfile` 
`source 'https://github.com/CocoaPods/Specs.git'`

this will tell the pod to use that git repository instead of the pod default repo and that will clone the repository(which is about 800MB) into your system and the will use that.
this solved the issue.
It's better to mention this in development documentation where it's just mention to run commands.
