### ISSUE TITLE
Installation error : Styled components should specify corresponding style name

### ISSUE THREAD

**Issue by TibReact** [akveo/kittenTricks#325]
## 🐛 Bug Report

Hello, after "expo init ", installing git repo and all modules I have the error below :

Styled components should specify corresponding style name.
at node_modules/@ui-kitten/components/theme/style/styled.js:44:8 in exports.styled
at src/components/status-bar.component.tsx:11:1 in StatusBar
at src/app/app.component.tsx:9:0 in <global>
at App.ts:1:0 in <global>
at node_modules/expo/AppEntry.js:3:0 in <global>
at http://192.168.1.11:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:310445:3 in global code

Unable to start your application. Please refer to https://expo.fyi/no-registered-application for more information.
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:200:6 in runApplication

TypeError: null is not a function (near '..._dec...')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

## To Reproduce

Install git repo and modules 

## Expected behavior

Launch of the application ;)

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.1.1    |
| @ui-kitten/components   |   5.1.1      |

## Environment information

System:
    OS: macOS 11.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 2021.09.13.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 27, 28
      Build Tools: 26.0.2, 27.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.2
      System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 

```

**Comment by TibReact** [comment]
@babel/plugin-proposal-decorators was missing ... All is fine.
