### ISSUE TITLE
Error while running npm install

### ISSUE THREAD

**Issue by shreyanshsaha** [akveo/kittenTricks#327]
## 🐛 Bug Report
console output
```bash
npm ERR! code EWORKSPACESCONFIG
npm ERR! workspaces config expects an Array

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shrey/.npm/_logs/2022-01-08T20_38_19_312Z-debug.log
````

file:  /home/shrey/.npm/_logs/2022-01-08T20_38_19_312Z-debug.log
```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '--legacy-peer-deps' ]
1 info using npm@7.5.2
2 info using node@v12.21.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/shrey/Downloads/kittenTricks/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/shrey/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 verbose npm-session 92a05858e8a034c7
20 timing npm:load Completed in 17ms
21 timing arborist:ctor Completed in 0ms
22 timing idealTree Completed in 6ms
23 timing command:install Completed in 21ms
24 verbose stack TypeError: workspaces config expects an Array
24 verbose stack     at getError (/usr/share/nodejs/@npmcli/map-workspaces/index.js:72:24)
24 verbose stack     at getPatterns (/usr/share/nodejs/@npmcli/map-workspaces/index.js:36:11)
24 verbose stack     at mapWorkspaces (/usr/share/nodejs/@npmcli/map-workspaces/index.js:88:20)
24 verbose stack     at Arborist.[loadWorkspaces] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/load-workspaces.js:20:30)
24 verbose stack     at /usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:297:42
24 verbose stack     at async Arborist.buildIdealTree (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:206:7)
24 verbose stack     at async Promise.all (index 1)
24 verbose stack     at async Arborist.reify (/usr/share/nodejs/@npmcli/arborist/lib/arborist/reify.js:127:5)
24 verbose stack     at async install (/usr/share/nodejs/npm/lib/install.js:38:3)
25 verbose cwd /home/shrey/Downloads/kittenTricks
26 verbose Linux 5.11.0-41-generic
27 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--legacy-peer-deps"
28 verbose node v12.21.0
29 verbose npm  v7.5.2
30 error code EWORKSPACESCONFIG
31 error workspaces config expects an Array
32 verbose exit 1
```
## To Reproduce

1. clone the repo
2. cd to the repo
3. run `npm install`

## Expected behavior

npm install should download the required deps

## Link to runnable example or repository (highly encouraged)
current repo

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     "@eva-design/eva": "^2.1.0"   |
| @ui-kitten/components   |      "@ui-kitten/components": "5.1.0"   |

## Environment information

```bash
shrey@ub:~/Downloads/kittenTricks$ npx envinfo --preset react-native
npm ERR! code EWORKSPACESCONFIG
npm ERR! workspaces config expects an Array

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shrey/.npm/_logs/2022-01-08T20_41_12_302Z-debug-0.log
```

**Comment by fl1jason** [comment]
Got exactly the same issue, are you using Expo 44?

**Comment by shreyanshsaha** [comment]
Hi @fl1jason, my expo-cli version is 5.0.3 and sdk version should be 43 based on this doc https://docs.expo.dev/versions/v44.0.0/
My react-native version is  0.64.3. I wasnt able to resolve this so I decided to download the app from app store instead.

**Comment by fl1jason** [comment]
@shreyanshsaha that’s a shame. I’ve managed to get Kitten UI working a treat in a new app I’ve built, but have given up with Kitten Tricks. :-(

**Comment by shreyanshsaha** [comment]
Yeah, the framework is working. You can still download the tricks from app store and check the code in the repo. Thats what I am doing. 
Hopefully this is resolved soon :crossed_fingers:

**Comment by fl1jason** [comment]
@shreyanshsaha yeah, that’s what I’m doing too. I’ll keep an eye on it.

**Comment by hesa2020** [comment]
Just fyi I had no issue running the package install using "yarn"

**Comment by tokomeno-kaltura** [comment]
npm i is still broken. any news?

**Comment by SuperBigBang** [comment]
> npm i is still broken. any news?

on package.json change: 
```
 "workspaces": {
    "nohoist": [
      "*",
      "*/**"
    ]
  },
```

to:
```
"workspaces": [
    "*",
    "*/**"
  ],
```
